# Generated by Django 5.2.7 on 2025-11-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('uname', models.CharField(max_length=100, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phonenum', models.CharField(max_length=20, verbose_name='电话号码')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
    ]
