# Generated by Django 5.2.7 on 2025-11-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='收藏记录ID')),
            ],
            options={
                'verbose_name': '收藏记录',
                'verbose_name_plural': '收藏记录',
                'db_table': 'collect',
                'managed': False,
            },
        ),
    ]
