# Generated by Django 5.2.8 on 2025-11-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='邮箱是否验证'),
        ),
    ]
