# Generated by Django 5.2.8 on 2025-12-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_is_email_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collect',
        ),
    ]
