# Generated by Django 5.2.8 on 2025-12-18 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_collect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='收藏记录ID')),
            ],
            options={
                'verbose_name': '收藏记录',
                'verbose_name_plural': '收藏记录',
                'db_table': 'collect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(db_column='uid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='users.users', verbose_name='用户')),
                ('signature', models.CharField(blank=True, default='无', max_length=200, verbose_name='个性签名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('secret', '保密')], default='secret', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('location', models.TextField(blank=True, verbose_name='所在地')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'db_table': 'profile',
            },
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
