# Generated by Django 5.2.8 on 2025-12-20 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_collect_profile_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
