# Generated by Django 5.2.8 on 2025-12-20 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_users_groups_users_is_active_users_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False, 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
