# Generated by Django 5.2.7 on 2025-11-19 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, verbose_name='分类名')),
            ],
            options={
                'verbose_name': '分类管理',
                'verbose_name_plural': '分类管理',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='电影名')),
                ('release_year', models.IntegerField(verbose_name='上映年份')),
                ('director', models.CharField(max_length=100, verbose_name='导演')),
                ('scriptwriter', models.CharField(max_length=100, verbose_name='编剧')),
                ('actors', models.CharField(max_length=200, verbose_name='主演')),
                ('region', models.SmallIntegerField(choices=[(1, '中国'), (2, '美国'), (3, '韩国'), (4, '日本'), (5, '其他')], verbose_name='地区')),
                ('types', models.CharField(max_length=50, verbose_name='类型')),
                ('language', models.CharField(max_length=100, verbose_name='语言')),
                ('release_date', models.DateField(verbose_name='上映日期')),
                ('duration', models.CharField(max_length=50, verbose_name='时长(或集数)')),
                ('alternate_name', models.CharField(blank=True, max_length=100, verbose_name='又名')),
                ('image_url', models.CharField(blank=True, max_length=300, verbose_name='图片链接')),
                ('rate', models.FloatField(blank=True, verbose_name='豆瓣评分')),
                ('review', models.TextField(blank=True, max_length=500, verbose_name='简介')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.category', verbose_name='分类名')),
            ],
            options={
                'verbose_name': '影视管理',
                'verbose_name_plural': '影视管理',
                'db_table': 'movie_and_tv',
            },
        ),
    ]
