# Generated by Django 5.2.8 on 2025-11-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=100, verbose_name='影视名'),
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movies_and_tv',
        ),
    ]
